### PR TITLE
Allow execution of system arguments directly

### PR DESCRIPTION
**Pull request by jimhester**
This can simplify use of pak in GitHub Actions and other CI systems.

### CODE REVIEW

**Comment by jimhester** [comment]
@gaborcsardi would love to hear if you have suggestions with the processx parts of this. In particular the word splitting and dealing with the command output.

**Comment by gaborcsardi** [comment]
Yeah, it is not great to take the command line apart. Should we run a shell instead? 

For the output, can you just pass `echo = TRUE`?

**Comment by jimhester** [comment]
I tried `echo = TRUE` first, but the output doesn't bubble up then to the main pak process.

Hmm maybe we could run a shell, I guess that would be an easy way to solve the issue. Presumably all the commands won't have any issues with quoting anyway...

**Comment by jimhester** [comment]
Thanks for reviewing!

**Pull request merged**
