### PR TITLE
Add global pak handler

### LINKED ISSUE #272: Offer package install condition handler
Listen to global package `packageNotFoundError` condition and offer to install package.

Could also restart in some situations, e.g. https://github.com/wch/r-source/blob/d23cb238e546b7a1e0339de1894ed2e356835b1e/src/library/base/R/namespace.R#L369

### PR DESCRIPTION
**Pull request by gaborcsardi**
Catches package loading failures, and offers installing the missing package.

Questions:
- [ ] Should we use `is_interactive()`, or just `interactive()`? Or neither, and this is up to the user?
- [ ] What if there is an active `sink()` and we cannot print to the screen?
- [ ] Should we have a `setup_global_handler()` function?
- [ ] Should we try to remove the handler when unloading?
- [ ] Should we ask the user about calling the restart instead of just calling it (if available)?
- [ ] Should we submit a patch to base R that moves the restart to `find.package()`, so that we'd have it for `library()` as well?

I have this in my `.Rprofile` currently, to try it out:
```r
if (interactive() && getRversion() >= "4.0.0") {
  globalCallingHandlers(
    packageNotFoundError = function(err) pak:::global_handler(err)
  )
}
```

Closes #272.

### CODE REVIEW

**Comment by hadley** [comment]
Cool! The interactive and sink behaviour seems right to me. I feel like everything else is ok for now? We can try it ourselves for a bit before documenting more widely.

**Comment by gaborcsardi** [comment]
OK, I'll write some minimal docs, and merge this, so it will be in the daily builds. We can then visit the questions above later, as needed.

**Comment by gaborcsardi** [comment]
@hadley Btw. `global_handler` is not the best name, what should we call this function?

**Comment by hadley** [comment]
Maybe `pak::install_if_missing()`?

**Comment by gaborcsardi** [comment]
> Maybe `pak::install_if_missing()`?

That's better, but also misleading, because it is an error handler callback, so you are not calling it directly. I was thinking something like `install_missing_handler()`?

**Comment by hadley** [comment]
Or make it a verb? `handle_package_not_found` ?

**Comment by gaborcsardi** [comment]
Yeah, let's go with that.

**Comment by gaborcsardi** [comment]
So the profile code is currently something like

```r
if (interactive() && getRversion() >= "4.0.0") {
  globalCallingHandlers(
    packageNotFoundError = function(err) {
      try(pak::handle_package_not_found(err))
    }
  )
}
```

it is getting a bit tedious, but you can copy it from the help page...

**Comment by hadley** [comment]
Why do you need the try? And presumably it's ok to omit the `iteractive()` check because that's handled internally?

**Comment by gaborcsardi** [comment]
> Why do you need the try? 

Just in case pak is not available, e.g. you start R with a minimal library. But yeah, maybe the `try()` is not great.

> And presumably it's ok to omit the iteractive() check because that's handled internally?

In the profile? Maybe, but it is cleaner not to set it up at all. E.g. no need to load pak in a non-interactive subprocess for this, only to fail.

Or in the handler? That's what I thought, but then undid it, just in case somebody is not using the suggested setup code.

**Pull request merged**
