### PR TITLE
Don't show error call

### LINKED ISSUE #221: Minor refinement to error message
If you mistype the name of a GitHub package, you currently get:

```
Error in remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...),  : 
  Cannot install packages:
  x Cannot install `r-lib/lookup`.
    - Cannot resolve GitHub repo `r-lib/lookup`. Could not resolve to a Repository with the name 'r-lib/lookup'.
```

I think this could just be:

```
Cannot install packages:
x Cannot install `r-lib/lookup`.
   Cannot resolve GitHub repo `r-lib/lookup`. Name not found.
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #221

### CODE REVIEW

**Comment by hadley** [comment]
Oh hmmmm, this comes from processx, so maybe the actual fix should be elsewhere

**Comment by gaborcsardi** [comment]
Ideally, we would just add `call. = FALSE` in pak somewhere. Is that not possible?

**Comment by hadley** [comment]
Just realised the _actual_ problem.

**Comment by hadley** [comment]
Ok look now — the problem is that there's a logic error, and a `NULL` call is always replaced with something.

**Comment by gaborcsardi** [comment]
Yeah, that makes sense, this is a good fix in general, I think.

**Comment by gaborcsardi** [comment]
Yeah, this breaks the tests in processx, unfortunately. I'll fix it in a sec.

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
