### PR TITLE
Add Ubuntu 22.04 to the list of supported OS versions

### PR DESCRIPTION
**Pull request by rstub**

### CODE REVIEW

**Comment by rstub** [comment]
Converting to draft mode since I currently get an error
```
Error in load_private_package("glue") : 
  Cannot load glue from the private library
```
independent of whether I use this patch or not. Need to figure that out, first.

**Comment by eitsupi** [comment]
Any update on this?

**Comment by gaborcsardi** [comment]
Note that pak does not use these functions when installing system requirements and they will be deprecated in the next release.

Nevertheless, if you think this is ready for review, then remove the "draft" status please.

**Comment by rstub** [comment]
At the moment one gets:

```
> pak::pkg_system_requirements("curl", os = "ubuntu", os_release = "22.04")
Error: 
! error in pak subprocess
Caused by error in `match.arg(os_release, os_versions[[os]])`:
! 'arg' should be one of “14.04”, “16.04”, “18.04”, “20.04”
Type .Last.error to see the more details.
```

With this patch one gets:

```
> pak::pkg_system_requirements("curl", os = "ubuntu", os_release = "22.04")
[1] "apt-get install -y libcurl4-openssl-dev libssl-dev"
```

@gaborcsardi If the patched function will become deprecated, what is the correct way to support Ubuntu 22.04?

**Comment by gaborcsardi** [comment]
> @gaborcsardi If the patched function will become deprecated, what is the correct way to support Ubuntu 22.04?

pak supports Ubuntu 22.04 already. If you opt in, it installs system requirements automatically, see "PKG_SYSREQS" here: https://pak.r-lib.org/reference/pak-config.html

**Comment by rstub** [comment]
That works with Ubuntu proper but not Ubuntu derived distributions, c.f. #396. In addition, I think it is useful to have a function that just returns the necessary package installation steps w/o executing them. Is there a replacement when `pak::pkg_system_requirements` gets deprecated?

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
