### PR TITLE
Use dev pkgbuild for dev pak

### PR DESCRIPTION
**Pull request by krlmlr**
For https://github.com/r-lib/pkgbuild/pull/157#issuecomment-1581392527.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
pak does not directly depend on pkgbuild, so this won't work, I am afraid, unless you add pkgbuild to `Suggests` and `Config/needs/dependencies` as well. Or you add pkgbuild to `Remotes` in pkgdepends.

**Comment by krlmlr** [comment]
Will it be enough to add only to `Config/Needs/dependencies`, without adding to `Suggests` ?

**Comment by gaborcsardi** [comment]
No.

**Comment by gaborcsardi** [comment]
New pkgbuild is on CRAN, so I guess this is not needed any more.

**Pull request closed without merging**
